# Generated by Django 4.0.4 on 2022-08-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('work_overview', models.TextField(blank=True)),
                ('work_file', models.FileField(blank=True, null=True, upload_to='TaskFile/')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('task_status', models.CharField(choices=[('Assigned', 'Assigned'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
