# Generated by Django 4.0.4 on 2022-08-26 08:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_picture', models.ImageField(upload_to='EmployeeProfileModel/employee_photo')),
                ('fullName', models.CharField(max_length=100)),
                ('employee_contact', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+?(88)01[3-9][0-9]{8}$')], verbose_name="Employee's Mobile phone")),
                ('Date_of_Birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], max_length=15)),
                ('employee_nid', models.IntegerField()),
                ('employee_address', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('employee_designation', models.CharField(max_length=100)),
                ('employee_salary', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('employee_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BossModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_picture', models.ImageField(upload_to='BossProfileModel/boss_photo')),
                ('fullName', models.CharField(max_length=100)),
                ('boss_contact', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+?(88)01[3-9][0-9]{8}$')], verbose_name="Employee's Mobile phone")),
                ('Date_of_Birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], max_length=15)),
                ('boss_nid', models.IntegerField()),
                ('boss_address', models.CharField(max_length=200)),
                ('boss_id', models.CharField(max_length=50, unique=True)),
                ('boss_designation', models.CharField(max_length=100)),
                ('boss_salary', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('head_of_dpt', models.CharField(choices=[('Accounts', 'Accounts')], max_length=200)),
                ('boss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boss_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
